---

- name: Modify ownership of the Laravel Log File
  shell: |
    echo "" >> /var/www/html/laravelapp/storage/logs/laravel.log
    chown www-data:www-data /var/www/html/laravelapp/storage/logs/laravel.log


- name: Change permission to the Laravel Log File
  shell: chmod 755 /var/www/html/laravelapp/storage/logs/laravel.log