---
 
  - name: Install package dependencies
    apt: name=software-properties-common

  - name: "Updating the repo"
    apt: update_cache=yes

  - name: Install PHP
    apt: name=php8.1 state=present

  - name: install lamp stack
    apt:
      pkg:
        - php8.1-mysql
        - php8.1-curl
        - php8.1-cgi
        - php8.1-xsl
        - php8.1-cgi
        - php8.1-gd
        - php8.1-mbstring
        - php8.1-zip
        - php8.1-xmlrpc
        - php8.1-soap
        - php8.1-intl
        - libapache2-mod-php
      state: present
      update_cache: yes
